# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-12 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloginhistory',
            old_name='username',
            new_name='browser',
        ),
    ]
