# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-12 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171212_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
