# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171212_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='ip',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
