# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171225_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', null=True),
        ),
    ]
