# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171225_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginhistory',
            options={'ordering': ('-time',)},
        ),
    ]
