# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='coin',
            new_name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='symbol',
            field=models.CharField(default='', max_length=200),
        ),
    ]
