# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20171223_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
