# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180113_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldassets',
            name='market_price',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='purchase_price',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='sell_price',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=20),
        ),
    ]
