# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
