# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180103_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
