# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180113_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=32),
        ),
    ]
