# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180103_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('note', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sold',
        ),
    ]
