# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180103_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
