# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180113_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldassets',
            name='purchase_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=32),
        ),
    ]
