# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
