# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
