# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180114_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldassets',
            name='purchase_price',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=32),
        ),
    ]
