# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180104_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldassets',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='transaction_date',
            field=models.DateField(blank=True),
        ),
    ]
