# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180105_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('-transaction_date',)},
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='soldassets',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='soldassets',
            name='price_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='buy_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sell_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='market_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='soldassets',
            name='sell_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
