# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20180107_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldassets',
            name='buy_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
