# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_soldassets_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldassets',
            old_name='price_type',
            new_name='buy_price_type',
        ),
        migrations.AddField(
            model_name='soldassets',
            name='sell_price_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
