# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20180109_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldassets',
            old_name='buy_price_type',
            new_name='price_type',
        ),
        migrations.RemoveField(
            model_name='soldassets',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='soldassets',
            name='sell_price_type',
        ),
        migrations.AddField(
            model_name='soldassets',
            name='asset_id',
            field=models.CharField(default='', max_length=2),
        ),
    ]
