# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20180109_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
